# Site settings

baseurl: "" # the subpath of your site, e.g. /portfolio
url: "" # the base hostname & protocol for your site
language: "" # language to set into html tag, default is en

# User settings

author: André "Kalavero" Veríssimo
author-title: Backend Developer
gravatar: 3a9860b7d5c0371d9bb896d4101b7a30
email: andrelucas.verissimo@yahoo.com
twitter: AndreKalavero
github: Kalavero
googleplus: AndreKalavero
facebook: andre.kalavero
linkedin: andrekalavero/en
bio: "Brazilian developer. Passionate about Technology, music, parkour and poker.
      I am a beckend developer and have tried many languages and frameworks since I first started in 2010.
      Sometimes I venture myself in working with frontend mostly using bootstrap.
      I am a self learner and enjoy learn any skill I can."

# Skills
#
# I'll use five differents levels:
# 1 - Studying: You know the basics of the skill and is studying it to get better
# 2 - Padawan: You know a little more than the basics and is comfortable to work with it
# 3 - Work with: You know how to handle the skill and how to properly use it in a real project
# 4 - Specialist: You have advanced knowledge of the skill and know how to use its best practices in a real project
# 5 - Jedi: You master the skill, know how and when to use and when not use it
#
# You can change these names in _includes/_skill-level-name.html if you wish
#
# If you don't want one of the sections below, leave the variable without any values
front-end:
  - name: HTML 5
    level: 4
  - name: CSS 3
    level: 3
  - name: JavaScript
    level: 3
  - name: Bootstrap
    level: 3

back-end:
  - name: Ruby
    level: 4
  - name: Python
    level: 4
  - name: C
    level: 4
  - name: C++
    level: 3
  - name: PHP
    level: 2
  - name: Java
    level: 2
  - name: SQL
    level: 2
  - name: Lua
    level: 1

mobile:
  - name: Android
    level: 2
  - name: IOS
    level: 2

db:
  - name: MySQL
    level: 3
  - name: PostgreSQL
    level: 3
  - name: MongoDB
    level: 2

devops:
  - name: Docker
    level: 3
  - name: Vagrant
    level: 3
  - name: Git
    level: 3
  - name: Continuous Integration
    level: 3
  - name: Continuous Delivery
    level: 3

methodologies:
  - name: Agile Methodologies
    level: 4
  - name: Scrum
    level: 3
  - name: RUP
    level: 2

others:
  - name: Django
    level: 3
  - name: Ruby on Rails
    level: 3
  - name: REST
    level: 3

# Build settings

markdown: kramdown
highlighter: rouge
sitemap: true # Generate sitemap.xml

sass:
  sass_dir: css
  style: compressed
## For more settings: https://jekyllrb.com/docs/configuration/

# exclude files if no need build
exclude: ['package.json', 'node_modules', 'README.md', 'LICENSE']

# Gems
gems: [jekyll-sitemap]
